[tasks."up"]
dependencies = ["install:sui", "install:gen", "ui:up"]

[tasks."install"]
dependencies = ["install:sui", "install:gen"]

[tasks."install:sui"]
script = '''
cargo install --git https://github.com/origin-byte/suivm
suivm use mainnet-v1.12.2
'''

[tasks."install:gen"]
script = '''
cargo install --locked --git https://github.com/kunalabs-io/sui-client-gen.git
'''

[tasks."ui:dev"]
script = '''
cd ui
bun run dev
'''

[tasks."ui:build"]
script = '''
cd ui
bun run build
'''

[tasks."ui:up"]
script = '''
cd ui
bun update
'''

[tasks."deploy:sui"]
script = '''
cd contracts/coco
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''

[tasks."create:event"]
script = '''
cd contracts/coco
PACKAGE=0x8fff73c650ca09e3fc21bdad276375b609ff041c66c2541c3543a2d69aa33e30
sui client call \
    --package $PACKAGE \
    --module issuer \
    --function create_event \
    --args \
        0x45e70a10bfe074f8be8f52483b87f5bafedc8c6084894874feb1ed0c6d5a22a3 \
        "movejp10" \
        "Sui POAP" \
        20000000000000 \
    --gas-budget 123456789
'''

[tasks."gen:sui"]
script = '''
cd ui/
bun run gen:sui
bun run lint
'''

[tasks."sui:switch:mainnet"]
script = '''
sui client switch --env mainnet
'''

[tasks."sui:add:mainnet"]
script = '''
sui client new-env --rpc "https://fullnode.mainnet.sui.io:443" --alias mainnet
'''

[tasks."sui:add:testnet"]
script = '''
sui client new-env --rpc "https://fullnode.testnet.sui.io:443" --alias testnet
'''
